# Generated by Django 2.2.10 on 2020-07-23 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('resolved', 'resolved'), ('discarded', 'discarded')], default='pending', max_length=250)),
                ('reported_on', models.DateTimeField(default=datetime.datetime(2020, 7, 23, 13, 34, 22, 814254))),
                ('user_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userIssues', to='accounts.Profile')),
            ],
            options={
                'verbose_name_plural': 'Report Issues',
            },
        ),
    ]
