# Generated by Django 2.2.10 on 2020-07-23 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0002_auto_20200723_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportissue',
            name='reported_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
