# Generated by Django 2.2.10 on 2020-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0003_auto_20200723_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportissue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
