# Generated by Django 2.2.10 on 2020-07-23 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import status.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Hashtags',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('background_color', models.CharField(max_length=12)),
                ('background_image', models.ImageField(upload_to='Status/background_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive'), ('deleted', 'deleted')], default='active', max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userStatus', to='accounts.Profile')),
                ('hashtags', models.ManyToManyField(blank=True, related_name='associatedHashtags', to='status.Hashtags')),
            ],
            options={
                'verbose_name_plural': 'Status Cards',
            },
        ),
        migrations.CreateModel(
            name='StatusFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=status.models.picture_upload_path)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusFiles', to='status.Status')),
            ],
            options={
                'verbose_name_plural': 'Status Associated Files',
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedBy', to='accounts.Profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedStatus', to='status.Status')),
            ],
            options={
                'verbose_name_plural': 'Liked Status',
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouriteSetBy', to='accounts.Profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouriteStatus', to='status.Status')),
            ],
            options={
                'verbose_name_plural': 'Favourites',
            },
        ),
    ]
