# Generated by Django 2.2.10 on 2020-07-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200726_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfiles',
            name='file_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
