# Generated by Django 2.2.10 on 2020-08-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_hashtags_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
