# Generated by Django 2.2.10 on 2020-08-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_status_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='background_color',
            field=models.CharField(max_length=30),
        ),
    ]
