# Generated by Django 2.2.10 on 2020-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20200824_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='Status/background_images/'),
        ),
    ]
