# Generated by Django 2.2.10 on 2020-07-23 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('accounts', '0002_profile_date_of_birth'),
        ('friends', '0002_auto_20200723_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='note',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='blockedusers',
            name='blocked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportusers',
            name='reported_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(blank=True, related_name='groupParticipants', to='accounts.Profile')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusGroup', to='status.Status')),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
