# Generated by Django 2.2.10 on 2020-07-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20200723_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('blocked', 'blocked')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
