# Generated by Django 2.2.10 on 2020-08-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200725_1447'),
        ('friends', '0005_auto_20200725_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='participants',
        ),
        migrations.AddField(
            model_name='groups',
            name='joined',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupParticipants', to='accounts.Profile'),
        ),
    ]
