# Generated by Django 2.2.10 on 2020-08-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_reportusers_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Status join Logs'},
        ),
    ]
