# Generated by Django 2.2.10 on 2020-08-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200725_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_server_admin',
            field=models.BooleanField(default=False),
        ),
    ]
